# Laboratory work No. 1

## Work topic: Binary relations
### The purpose of the work: studying the properties of binary relations, operations on relationships, acquiring decision-making skills based on the given relations
### Variant 7

In [44]:
import numpy as np

In [45]:
R = np.array([[1, 0, 0, 0, 0],
             [0, 1, 0, 1, 0],
             [1, 1, 1, 1, 1],
             [1, 0, 0, 1, 1],
             [0, 1, 0, 0, 1]])

### Reflexivity

In [46]:
r = 1
for i in range(5):
    if R[i][i] == 0:
        r = 0
        break
if r:
    print("The relationship is reflexive")
else:
    print("The relationship is not reflexive")

The relationship is reflexive


### Anti-reflexivity

In [47]:
r = 1
for i in range(5):
    if R[i][i] == 1:
        r = 0
        break
if r:
    print("The relationship is anti-reflexive")
else:
    print("The relationship is not anti-reflexive")

The relationship is not anti-reflexive


### Symmetry

In [48]:
r = 1
for i in range(5):
    for j in range(5):
        if R[i][j] != R[j][i]:
            r = 0
            break
if r:
    print("The relationship is symmetrical")
else:
    print("The relationship is not symmetrical")

The relationship is not symmetrical


### Anti-symmetry

In [49]:
r = 1
for i in range(5):
    for j in range(5):
        if i != j and R[i][j] == 1 and R[j][i] == 1:
            r = 0
            break
if r:
    print("The relationship is anti-symmetrical")
else:
    print("The relationship is not anti-symmetrical")

The relationship is anti-symmetrical


### Asymmetry

In [50]:
r = 1
for i in range(5):
    for j in range(5):
        if R[i][j] == 1 and R[j][i] == 1:
            r = 0
            break
if r:
    print("The relationship is asymmetrical")
else:
    print("The relationship is not asymmetrical")

The relationship is not asymmetrical


### Transitivity

In [51]:
r = 1
R2 = R ** 2
for i in range(5):
    for j in range(5):
        if R2[i][j] <= R[j][i]:
            r = 0
            break
if r:
    print("The relationship is transitive")
else:
    print("The relationship is not transitive")

The relationship is not transitive


### Inverse Relation

In [52]:
R_inv = np.zeros((5, 5), dtype=int)
for i in range(5):
    for j in range(5):
        R_inv[i][j] = R[j][i]
print(R_inv)

[[1 0 1 1 0]
 [0 1 1 0 1]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]]


### Additive Relation

In [53]:
R_add = 1 - R
print(R_add)

[[0 1 1 1 1]
 [1 0 1 0 1]
 [0 0 0 0 0]
 [0 1 1 0 0]
 [1 0 1 1 0]]


###  Maximum and Minimum elements

In [54]:
R_s = R - R_inv

min_elements = np.where(np.all(R_s == 0, axis=0))[0]
max_elements = np.where(np.all(R_s == 0, axis=1))[0]

if min_elements.size > 0:
    print("The best elements:")
    for i in min_elements:
        print(f"x_{i+1} ")
else:
    print("No best element")

if max_elements.size > 0:
    print("The worst elements:")
    for i in max_elements:
        print(f"x_{i+1} ")
else:
    print("No worst element")

No best element
No worst element


### Best and Worst elements

In [55]:
best_elements = np.where(np.all(R == 1, axis=1))[0]
worst_elements = np.where(np.all(R == 1, axis=0))[0]

if best_elements.size > 0:
    print("The best elements:")
    for i in best_elements:
        print(f"x_{i+1} ")
else:
    print("No best element")

if worst_elements.size > 0:
    print("The worst elements:")
    for i in best_elements:
        print(f"x_{i+1} ")
else:
    print("No worst element")

The best elements:
x_3 
No worst element
