# Лабораторна робота No 2

### Тема роботи: Розв’язування задач багатокритерійної оптимізації.
### Мета роботи: вивчення методів розв’язування задач багатокритерійної оптимізації.
### Варіант 7

In [22]:
import numpy as np
from scipy.optimize import linprog

In [23]:
profit = np.array([22, 18, 30])

time_matrix = np.array([
    [1, 0.9, 1.1, 1.2, 1.5, 0, 0.9, 0, 0],
    [0.8, 0.8, 1.3, 0.9, 1.1, 1.3, 1.1, 0.8, 0],
    [0, 0.7, 0.7, 0.7, 0, 1.3, 1.3, 0.6, 0]
])

time_resources = np.array([200, 400, 300])

In [24]:
A_ub = np.vstack([time_matrix, np.ones(9)])
b_ub = np.append(time_resources, 500)

c = -np.tile(profit, 3)

x_bounds = [(0, None)] * 9

In [25]:
print("Перевірка обмежень")
for i, row in enumerate(A_ub):
    print(f"Обмеження {i + 1}: сума мінімальних потреб {sum(np.minimum(row, b_ub[i]))}, доступно {b_ub[i]}")

Перевірка обмежень
Обмеження 1: сума мінімальних потреб 6.6000000000000005, доступно 200
Обмеження 2: сума мінімальних потреб 8.100000000000001, доступно 400
Обмеження 3: сума мінімальних потреб 5.299999999999999, доступно 300
Обмеження 4: сума мінімальних потреб 9.0, доступно 500


In [26]:
res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=x_bounds, method='highs')

In [27]:
if res.success:
    optimal_hours = res.x.reshape(3, 3)
    optimal_profit = -res.fun
    print("Оптимальний розподіл годин:")
    print(optimal_hours)
    print("Максимальний прибуток:", optimal_profit)
else:
    print("Не вдалося знайти оптимальне рішення")
    print("Статус:", res.message)

Оптимальний розподіл годин:
[[  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0. 500.]]
Максимальний прибуток: 15000.0
