In [18]:
import numpy as np

In [19]:
R1 = np.array([
    [1.0, 0.3, 0.4, 0.5, 0.1],
    [0.3, 1.0, 0.7, 0.3, 0.7],
    [0.9, 0.0, 1.0, 0.9, 0.7],
    [0.3, 0.5, 0.6, 1.0, 0.4],
    [0.2, 0.5, 0.7, 0.9, 1.0]
])

R2 = np.array([
    [1.0, 0.0, 1.0, 0.0, 0.6],
    [0.1, 1.0, 0.5, 0.4, 0.3],
    [0.5, 0.7, 1.0, 0.0, 0.7],
    [0.5, 0.3, 0.0, 1.0, 0.7],
    [0.7, 0.9, 0.8, 0.5, 1.0]
])

lambda1 = 0.7
lambda2 = 0.3

In [20]:
Q1 = np.minimum(lambda1 * R1, lambda2 * R2)
print(Q1)

[[0.3  0.   0.28 0.   0.07]
 [0.03 0.3  0.15 0.12 0.09]
 [0.15 0.   0.3  0.   0.21]
 [0.15 0.09 0.   0.3  0.21]
 [0.14 0.27 0.24 0.15 0.3 ]]


In [21]:
Q2 = lambda1 * R1 + lambda2 * R2
print(Q2)

[[1.   0.21 0.58 0.35 0.25]
 [0.24 1.   0.64 0.33 0.58]
 [0.78 0.21 1.   0.63 0.7 ]
 [0.36 0.44 0.42 1.   0.49]
 [0.35 0.62 0.73 0.78 1.  ]]


In [22]:
def calculate_difference_matrix(Q):
    n = Q.shape[0]
    Q_revers = np.zeros((n, n), dtype=float)
    Q_diff = np.zeros((n, n), dtype=float)

    # Reverse the matrix
    for i in range(n):
        for j in range(n):
            Q_revers[i][j] = Q[j][i]

    # Compute the difference
    for i in range(n):
        for j in range(n):
            Q_diff[i][j] = Q[i][j] - Q_revers[i][j]
            if Q_diff[i][j] < 0:
                Q_diff[i][j] = 0

    return Q_diff

Q1_diff = calculate_difference_matrix(Q1)
Q2_diff = calculate_difference_matrix(Q2)

In [23]:
print(Q1_diff)

[[0.   0.   0.13 0.   0.  ]
 [0.03 0.   0.15 0.03 0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.15 0.   0.   0.   0.06]
 [0.07 0.18 0.03 0.   0.  ]]


In [24]:
print(Q2_diff)

[[0.   0.   0.   0.   0.  ]
 [0.03 0.   0.43 0.   0.  ]
 [0.2  0.   0.   0.21 0.  ]
 [0.01 0.11 0.   0.   0.  ]
 [0.1  0.04 0.03 0.29 0.  ]]


In [25]:
def calculate_alternatives(Q_diff):
    n = Q_diff.shape[0]
    alternatives = np.zeros(n, dtype=float)

    for i in range(n):
        alternatives[i] = round(1 - max(Q_diff[:, i]), 3)

    return alternatives

def calculate_alternatives_in_both(alternatives1, alternatives2):
    return np.minimum(alternatives1, alternatives2)

In [26]:
alternatives_Q1 = calculate_alternatives(Q1_diff)
alternatives_Q2 = calculate_alternatives(Q2_diff)

In [27]:
print(alternatives_Q1)

[0.85 0.82 0.85 0.97 0.94]


In [28]:
print(alternatives_Q2)

[0.8  0.89 0.57 0.71 1.  ]


In [29]:
alternatives_in_Q1_and_Q2 = calculate_alternatives_in_both(alternatives_Q1, alternatives_Q2)

print('Alternatives in Q1 and Q2:\n', alternatives_in_Q1_and_Q2)

Alternatives in Q1 and Q2:
 [0.8  0.82 0.57 0.71 0.94]
